### ISSUE TITLE
don't set keymap prefix by default to [C-c /]

### ISSUE THREAD

**Issue by stardiviner** [hrs/engine-mode#27]
=[C-c /]= it is conflict with org-mode sparse tree keybinding.

```elisp
(engine/set-keymap-prefix (kbd "C-c /"))
```

Disable it or bind to not used `[C-x /]`.

**Comment by hrs** [comment]
Hey @stardiviner! Thanks for the suggestion; that's something I've been thinking about for a while, too. `C-x /` might be a good binding.

It's tricky to just do this, though, since it's a breaking change and might unpleasantly surprise users. I think I'd like hold off on this for a bit, queue it up with a few other breaking changes, and release them all together as 2.0.0. Does that sound reasonable to you?

**Comment by stardiviner** [comment]
It's fine. Because I comment out that like in source code file. Currently Emacs will not set it globally.
And I think it can be better to let user decide whether want this default keybinding with a customize option.

**Comment by stardiviner** [comment]
@hrs Hi, what's the progress? I found engine-mode updated, and I have to modify the source again. Is there a better solution? I think the `defcustom` is the user, they will not be unpleasant.

**Comment by hrs** [comment]
I believe this has been fixed in https://github.com/hrs/engine-mode/pull/28. Thanks, @stardiviner!
