### ISSUE TITLE
How to use queries like who and where?

### ISSUE THREAD

**Issue by faaafo** [hrs/engine-mode#50]
Say I want "foo bar" to search `phone.com?who=foo&where=bar.

How would I do that? 

Idiomatic thought was `%s`,`%s1` etc. though that's not working.

**Comment by hrs** [comment]
Hi there, @faaafo! In short, `engine-mode` doesn't support multiple keywords, and I don't plan to add that support. I suspect multiple keywords would be messy to implement: splitting marked text on whitespace introduces ambiguities, and multiple prompts for search terms would require associated keywords (since you'd probably want to see `Search phone.com for who:`, not `Search phone.com for 1:`, etc.

Also, the `%s` syntax is based on [Firefox keyword searches](https://support.mozilla.org/en-US/kb/how-search-from-address-bar), which similarly only take one argument, and I'd like to remain consistent with that.

If you'd like to write a function for your own configuration that does something like this, though, you could probably start by copying and modifying the [expression that interpolates keywords and opens the browser](https://github.com/hrs/engine-mode/blob/e0910f141f2d37c28936c51c3c8bb8a9ca0c01d1/engine-mode.el#L112-L114). Add a couple of custom prompts, modify the call to `format-spec` to add more arguments, bind it to a key, and I *think* you might be all set.
