### ISSUE TITLE
Binding an engine to a non-prefix key sequence?

### ISSUE THREAD

**Issue by benthamite** [hrs/engine-mode#56]
I have over a hundred search engines I use with some regularity, so I would like to bind some engines to a sequence of keys. Example:

``` emacs-lisp
  (defengine Wikipedia-English
    "https://en.wikipedia.org/w/index.php?search=%s"
    :keybinding "w e")
    (defengine Wikipedia-Spanish
    "https://es.wikipedia.org/w/index.php?search=%s"
    :keybinding "w s")
```

However, it appears that this isn't possible: when I evaluate those forms, I get "general-unbind-non-prefix-key: Key sequence w s starts with non-prefix key w". Note that it does work if instead I use a prefix key (e.g. `:keybinding "C-w e"`). But ideally bindings involving sequences of "non-prefix keys" should also be supported (since e.g. `C-x / w e` is a valid key binding).

**Comment by hrs** [comment]
Thanks for the report, @benthamite! That's totally something we should support, and I *think* it ought to be fixed in https://github.com/hrs/engine-mode/commit/00e0dde543e36745c8a14165bc0c9871468f7f3f. It should be available on MELPA shortly, so try updating the package and please let me know if you're still having trouble with it!

**Comment by benthamite** [comment]
Excellent––I confirm it works. Thank you!
